### PR TITLE
Potential settings object

### PR DESCRIPTION
**Pull request by cheddar**
@jebeck @skrugman @kentquirk 

This is a pull request with an example "settings" object.  I'm intending that any time even **_one**_ of the data points in these items changes, we get a brand new object with **_all**_ of the "current" values.  We will store the stream of all schedules that have existed.

Does this make sense to you?  It should be pretty straight-forward to generate this data from medtronic, I haven't dug into animas yet, though, so when I do get around to that, some things might change around.  I'm not planning on diving into animas until I'm done with medtronic stuff, though.  

Just from a high level, it seems like all pumps should have some measure of these ideas though.  The question for Animas will be more around if they expose the stuff to us or not.

Also, a point on organization of this repo.  I don't understand the organization of this repository and I just wanted to show an example file, so I put it here.  If you would rather this be somewhere else, just let me know (or feel free to just move it around).

On the names of the fields, I think they are intuitive and just make sense given the data we are working with.  I'm not attached to any of them though, if you want them changed or want an explanation of the data type, lmk.

### CODE REVIEW

**Comment by bewest** [comment]
Howdy,

The project is organized so that a test script can automatically find examples to test against different validators.
This makes it easy to automatically test all examples across a matrix of validators.

Improvements and patches are of course welcome.

**Comment by bewest** [comment]
@kentquirk the medtronic data is explicit about which units are being used.  We are deleting that data right now.

Animas data also has a spreadsheet for settings: https://github.com/tidepool-org/animas-diasend-data/blob/master/examples/Insulin-pump-settings.csv for comparison.

**Comment by kentquirk** [comment]
So the data-model is for the stuff we store, correct? I want Tidepool to be explicit about units that we present. It's OK to me if we document that they're mg/dl or whatever -- we don't have to store the units in the data file -- but if we don't, we should convert units that aren't in that form.

**Comment by bewest** [comment]
There are schemas pending in data-model for:
- vendor specific parser output `vendors/...`
- tidepool normalized output (what is mongo), aka `persisted`
- the visualization output, aka `diabetes`

So there is room in the data-model for all of our schemas.
In the future we might add user profiles, groups, etc...

**Comment by cheddar** [comment]
Good call on the units.  I just noticed that they snuck the units away inside of a different event, I'll add that.

**Comment by cheddar** [comment]
Ok, added units for everything but the basal profile.  I don't believe there is variance in units of insulin, is there?

**Comment by bewest** [comment]
For insulin "unit" is the unit.
Howard has more detail on this.

One international unit http://en.wikipedia.org/wiki/International_units of
insulin (1 IU) is defined as the "biological equivalent" of 34.7
ìghttp://en.wikipedia.org/wiki/Microgram pure
crystalline insulin. This corresponds to the old
USPhttp://en.wikipedia.org/wiki/United_States_Pharmacopeia insulin
unit, where one unit (U) of insulin was set equal to the amount required to
reduce the concentration of blood
glucosehttp://en.wikipedia.org/wiki/Blood_sugar in
a fasting http://en.wikipedia.org/wiki/Fasting
rabbithttp://en.wikipedia.org/wiki/Rabbit to
45 m http://en.wikipedia.org/wiki/Milli-ghttp://en.wikipedia.org/wiki/Gram
/d http://en.wikipedia.org/wiki/Deci-lhttp://en.wikipedia.org/wiki/Liter
 (2.5 m http://en.wikipedia.org/wiki/Milli-molhttp://en.wikipedia.org/wiki/Mole_(unit)
/L http://en.wikipedia.org/wiki/Liter).

The unit of measurement
http://en.wikipedia.org/wiki/Units_of_measurement used
in insulin therapy is not part of the International System of
Unitshttp://en.wikipedia.org/wiki/International_System_of_Units
(abbreviated
SI) which is the modern form of the metric
systemhttp://en.wikipedia.org/wiki/Metric_system.
Instead the pharmacological
http://en.wikipedia.org/wiki/Pharmacology international
unit http://en.wikipedia.org/wiki/International_units (IU) is defined by
the WHO Expert Committee on Biological
Standardizationhttp://en.wikipedia.org/wiki/WHO_Expert_Committee_on_Biological_Standardization
.[33] http://en.wikipedia.org/wiki/Insulin_therapy#cite_note-33
http://en.wikipedia.org/wiki/Insulin_therapy

**Comment by kentquirk** [comment]
Ok, but rate implies time. So it's units of insulin/hour? We should say so in the documentation anyway.

**Comment by bewest** [comment]
Sorry about the bad paste earlier.
To add a little more context for the other settings, the concept of settings on a schedule is relatively new.  Most pumps in use have this concept, and so it works even for flat rate schedules.  Some older models of pumps, eg `MM512`, `MM508` just have a single eg `sensitivity` value, eg `sensitivity: 45`, and are not expressed on a schedule.  I don't have enough information to know how many pumps are like that; for the ones that are, it's probably acceptable to transform them into a 1 rate schedule with an annotation.

Overall, it looks good to me, FWIW.

If you plan on developing a schema to test this example, you might want to move it under `examples/one/...` so that it is in a location parallel to the schema, and then include a reference to it in the tests list: https://github.com/tidepool-org/data-model/blob/master/tests/test_one_is_one.js#L16

**Comment by HowardLook** [comment]
“U” or "Units” of insulin of insulin is a measure of biological effect, not of volume.

But, since most people use 100U insulin (which tells you it’s concentration), “1U” of insulin  .01 ml of volume. Unfortunately “1U” has become synonymous with “.01 ml” for many many people. Doctors and people want to know the biological effect amount of insulin delivered, so it gets reported in Units.

But many people with small children (with very low insulin needs) use diluted, or 10U insulin. Some use 50U. Some people with very high insulin needs use extra concentrated insulin, so U200 or U500 insulin.

My favorite resources on the topic:
http://rushakoff.com/rushakoff/rushakoff2/page_37.html

http://rushakoff.com/rushakoff/rushakoff2/page_39.html

http://www.childrenwithdiabetes.com/cgi/cwdprintpage.cgi?url=http://www.childrenwithdiabetes.com/dteam/1996-08/d_0d_17h.htm

I would suggest be precise and store “units delivered” and store the concentration of insulin (which we can assume to be 100U, as long as it’s not overridden.

**Comment by bewest** [comment]
FWIW, Medtronic has overrides set in a variety of places to note when the pump is using some non-default insulin, but I don't know about other pumps.

**Comment by cheddar** [comment]
@HowardLook I'd like to table table insulin concentrations for pilot, please let me know if that is a complete no-go.  Silence will be compliance ;)

**Comment by HowardLook** [comment]
Fine by me. I was just providing requested information.

**Comment by cheddar** [comment]
Great @HowardLook 

Actually, thinking about how to handle them in the future, I got to wondering if there is actually meaning in having the units apply to each item of a schedule rather than be global for the schedule.  I just pushed a change that moves all of the units to a top-level item.

This is probably fine for everything except maybe carbRatio.  For some reason, medtronic has a units next to each carbRatio entry.  @HowardLook @bewest @jebeck Is it possible to enter individual carb ratios as different units?  It doesn't seem like it would be all that useful and would actually be a potential source of error that we might want to notify users about if they have different units set?

**Comment by cheddar** [comment]
Just got confirmation from Ben in chat that **_all**_ unit settings on a medtronic are global settings.  So even though the data is showing a unit per carbRatio item, a normal user can only set it globally.

So, this is extra evidence that it should be safe to treat units globally instead of per-item.

Ben also verified with Asante and they just force you to use carbs.

**Comment by jebeck** [comment]
LGTM in general. Only question is are we certain these are the only settings we want to expose for the pilot? This matches what's in the master file, so as long as that's truly all we want, we should be fine.

**Comment by cheddar** [comment]
Fwiw, I don't really see many other settings we can pull out of the file.  But I also haven't done an exhaustive exploration of all possible event types either...

I'm going to operate under the assumption that this is all we need unless told otherwise.

**Comment by bewest** [comment]
You are looking at the event types starting with `Current`?  These are all settings.

**Comment by cheddar** [comment]
Most of my exploration has been around changes, haven't explored the current set of events much 'cause I assumed they would require the least amount of interpretation.

It's a good point that they are the set of objects to check for what kinds of settings there are records of.

**Comment by jebeck** [comment]
FWIW, the other possible settings I can think of that exist are whether
percentage or manual is being used for temp basals, whether there's a
timeout set if you don't touch the pump for X hours (although IDK if
Medtronic has this?), daily maxes for basal and bolus, alarm volume, low
reservoir alert...

**Comment by cheddar** [comment]
Hrm, ok.
1. temp basals percentage or manual -- we agreed to store these as absolute unit amounts anyway, so the setting doesn't really matter
2. timeout -- if you don't touch the pump seems rather esoteric?  If we care about what happens when the pump times out, I'd rather track down the "I timed out event" and surface that
3. maxes for basal/bolus -- these might be good to know?
4. Alarm volume -- not important?
5. Low reservoir alert -- these are similar to timeouts, I think?

**Pull request merged**
