### PR TITLE
Add v1 documentation of "incoming" data format

### PR DESCRIPTION
**Pull request by cheddar**
@HowardLook @jebeck @brandonarbiter @kentquirk @cmakler 

This is a pull request that starts the documentation of what I am hoping to call the "Tidepool data format v1.0".  The intent of this document is that it shows the events that Tidepool understands. The document should actually be reusable as something that we give to vendors to start a conversation with them about what makes the most sense for emitting data.

One assumption I've made with the event structure is that I am trying to make a set of events that are friendly to a device that simply emits an event when it does something.  So, it should be a format that we can also expose to the WeAreNotWaiting crowd as something their Android devices could emit and get data into the tidepool platform in real-time.

This format is the output format of the "parsers".

The reason I am creating this document now is because when I explored the issues with basal display and Howard's fakabetic episodes, I realized that there were some things that we hadn't accounted for in the data as of yet.  Namely, the premature canceling of temp basals.  After thinking about how we can handle that, I felt it best to actually extend our data model with another event that indicates the premature termination of a temp basal.  I'm fine making this decision uni-laterally, but I figured it best to at least fish for buy-in first and the best way to do that seemed to be to document what we have and try to explain the use-case through that documentation.  Thus, we have this.

So, to be clear, I've only documented the basal data formats so far.  The initial "scheduled" and "temp" events are things that we are generating today in the parsers and I do not believe are controversial.  The "temp/stop" is a new event that I am proposing we add as a method of indicating that a temp basal has been canceled.

I am hoping for this to spark two conversations:

1) Agreement or disagreement on having a "temp/stop" event in our "standard data format"
2) Discussion of the perceived value of this document, the specification of our format and the strategy for proselytizing our format

I need a conclusion on (1) quickly (within the bounds of tomorrow would be great).  So please review the content of what I've written, respond with questions if you do not understand, and maybe we jump on a hangout tomorrow to discuss.

I do not think that pilot needs to block on (2), but a well-defined format is something I strongly want to push out to the world and I want to do everything I can to ensure that the conversation eventually happens.

### CODE REVIEW

**Comment by cheddar** [comment]
Btw, after having done this, I just realized that there might be some overlap with what is on the wiki on this repo already.  If that is the better place to add this, let me know and I'll either add a page or adjust the existing pages to contain this content.

There's no easy way to ask for feedback on wiki changes before they are applied, however, so I'd still like to request a discussion here before I edit the wiki.

**Comment by HowardLook** [comment]
l;r

I love the idea of having a document. I imagine us having lots of similar
documents that eventually make up a "best practices for device makers"
education.

I think I support having the temp/stop event. It makes sense to me that we
would have it.

On Wed, Mar 19, 2014 at 9:37 PM, cheddar notifications@github.com wrote:

> @HowardLook https://github.com/HowardLook @jebeckhttps://github.com/jebeck
> @brandonarbiter https://github.com/brandonarbiter @kentquirkhttps://github.com/kentquirk
> @cmakler https://github.com/cmakler
> 
> This is a pull request that starts the documentation of what I am hoping
> to call the "Tidepool data format v1.0". The intent of this document is
> that it shows the events that Tidepool understands. The document should
> actually be reusable as something that we give to vendors to start a
> conversation with them about what makes the most sense for emitting data.
> 
> One assumption I've made with the event structure is that I am trying to
> make a set of events that are friendly to a device that simply emits an
> event when it does something. So, it should be a format that we can also
> expose to the WeAreNotWaiting crowd as something their Android devices
> could emit and get data into the tidepool platform in real-time.
> 
> This format is the output format of the "parsers".
> 
> The reason I am creating this document now is because when I explored the
> issues with basal display and Howard's fakabetic episodes, I realized that
> there were some things that we hadn't accounted for in the data as of yet.
> Namely, the premature canceling of temp basals. After thinking about how we
> can handle that, I felt it best to actually extend our data model with
> another event that indicates the premature termination of a temp basal. I'm
> fine making this decision uni-laterally, but I figured it best to at least
> fish for buy-in first and the best way to do that seemed to be to document
> what we have and try to explain the use-case through that documentation.
> Thus, we have this.
> 
> So, to be clear, I've only documented the basal data formats so far. The
> initial "scheduled" and "temp" events are things that we are generating
> today in the parsers and I do not believe are controversial. The
> "temp/stop" is a new event that I am proposing we add as a method of
> indicating that a temp basal has been canceled.
> 
> I am hoping for this to spark two conversations:
> 
> 1) Agreement or disagreement on having a "temp/stop" event in our
> "standard data format"
> 2) Discussion of the perceived value of this document, the specification
> of our format and the strategy for proselytizing our format
> 
> I need a conclusion on (1) quickly (within the bounds of tomorrow would be
> great). So please review the content of what I've written, respond with
> questions if you do not understand, and maybe we jump on a hangout tomorrow
> to discuss.
> 
> I do not think that pilot needs to block on (2), but a well-defined format
> is something I strongly want to push out to the world and I want to do
> 
> ## everything I can to ensure that the conversation eventually happens.
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/tidepool-org/data-model cheddar/v1-format
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/tidepool-org/data-model/pull/18
> Commit Summary
> - Add v1 documentation of "incoming" data format
> 
> File Changes
> - _A_ schemata/v1.mdhttps://github.com/tidepool-org/data-model/pull/18/files#diff-0(103)
> 
> Patch Links:
> - https://github.com/tidepool-org/data-model/pull/18.patch
> - https://github.com/tidepool-org/data-model/pull/18.diff
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/tidepool-org/data-model/pull/18
> .

## 

Howard Look
President and CEO, Tidepool
howard@tidepool.org
C: 650-823-0021

Tidepool is an open source, not-for-profit effort to build an open data
platform and better applications that reduce the burden of Type 1 Diabetes
and accelerate the commercialization of closed-loop systems.

**Comment by kentquirk** [comment]
Is there any value in saying that "basal-stop" events happen (or can happen) even for basals that terminate normally (i.e., by timing out)? I could imagine a pump that emits a basal-stop event every time a temp basal ends, whether or not it was cancelled early.

Feels like this is the kind of thing that might be emitted by some devices as a reasonable design decision, so I wouldn't want us to be unable to handle extra events that aren't strictly needed.

**Comment by cheddar** [comment]
Sure, @kentquirk I don't see a reason why we wouldn't be able to support that.

Just to be clear these are "temp-stop" events, we are not expecting them for normal scheduled basals.  (You called them "basal-stop" events, so I wanted to make sure that was a typo and not something more meaningful)

**Comment by brandonarbiter** [comment]
Eric, thanks for taking a stab at this. It looks great. I like the way
you've handled temp-stop. I do have one piece of feedback with respect to
"duration".

AFAIK pumps do not consider the notion of "duration" for a normal basal
schedule; instead, they are driven by the notion of an "end time". This
becomes relevant if the device's time setting is changed in the middle of a
basal rate. (On a Medtronic pump, the device time cannot be changed while a
temp basal is in progress.)

It can easily happen that the new time is associated with a different basal
rate, even though the "elapsed time" since the original basal started
hasn't yet achieved its expected "duration". The basal schedule would still
progress to the next rate in accordance with the time change.

That said, "duration" is very relevant to a temp basal. I would think it
would only make sense to keep the notion of duration under temp basals. I
see that you've proposed having the same format for both standard basal
rates and temp basal rates. This might throw a wrench in that... or maybe
not, interested in your thoughts.

Thanks,
Brandon

Brandon Arbiter
VP, Product + Biz Dev
Tidepool http://www.tidepool.org | brandon@tidepool.org
917.536.0505 (m)

**Comment by cheddar** [comment]
Hrm, good point.  I'm definitely proposing to have a "duration" called out for scheduled basals as well.  Note that the "duration" is a best "guess" (i.e. what the pump believes at the time that it generates the event) of how long the basal will actually last, it's not necessarily gospel.

I think that the "time was changed, therefore the scheduled basal is going to last shorter/longer" case could be handled by the pump generating another basal event with the duration set to the amount of time that it will run given the time change.

**Comment by cmakler** [comment]
Since this piece of data represents a forward-looking prediction that the pump makes, should we call it “predicted_duration” rather than “duration”? We could then have an “actual_duration” or “computed_duration” function that would look at the time series of pump events and return the actual duration (to the best of our ability to understand) — that would not be part of the data model, of course, but could be part of the API (and would therefore be clearly identified as a computed, not recorded, value).

**Comment by cheddar** [comment]
I'm not sure I understand the importance of renaming.

A part of our processing should be able to smoosh together "scheduled" basals with the same rate and get just one of them with the "correct" duration.  Fwiw, this is the exact same semantics as "duration" for temp basals, so if we _do_ change the name, then we should change it for temp basals as well.

**Comment by cmakler** [comment]
The issue is that a data model should reflect actual data, not guesses or inferences (however good); and the names of the fields in the data should be as descriptive as possible for the sake of clarity.

To see why, consider this exact example. Suppose a pump manufacturer were to come up with a data model that did report an exact duration. If we had data from that pump and data from pumps that reported a predicted duration, we would want the data streams from those two pumps to reflect this distinction.

There are of course various methods of arriving at that same information. You could, for example, have a “duration_method” field that could take on values like “computed” or “reported.” I’m not proposing one particular solution versus another. But I am saying that we should not store computed information as if it were reported.

**Comment by cheddar** [comment]
The thing is, it is impossible for a device to a priori know how long the duration will actually be.  The duration can only be known to be 100% accurate when the duration is complete.  If we want to require that from devices, then we can never actually show what is happening "now" 'cause we will always have to wait for the basal to complete.

I don't really care about names too much, I just don't think that there is interesting semantic difference here, as I do not believe it is realistically possible to have any other semantics around what we receive.

**Comment by cmakler** [comment]
Yep, you make my point. If it's impossible to know a priori what the duration will be, that should be reflected in the event being reported. Adding "predicted_" to "duration" increases the accuracy of the event being reported, since the device (as you say) is reporting its expected duration.

On the other hand, if we are downloading data ex post, the device may report actual durations.

Indeed, a complete data picture should have both. For example:

5:37pm user sets to deliver 2 units over 1 hour
6:07pm user cancels; actual delivery was 1 unit over 1/2 hour

Both the predicted and actual duration are useful to have when analyzing what happened that afternoon. So we would want to have both predicted_duration = 1 and actual_duration = 0.5 as part of this event. Or, even better, just have the raw data stream (start 1 hour at 5:37, cancel at 6:07) and let the actual duration be a computation rather than a data point.

**Comment by cmakler** [comment]
Thinking about this further, as a more general issue related to the data model.

I believe we want to do two things before putting pen to paper for the data model:

(a) specify uses cases that the data model should handle. Because we are modeling behavior, the data model documentation should reflect not only the values storable in “tidepool format” data, but the data-generating process. This will both provide clarity to users and make our assumptions (e.g., “all duration data is predictive when reported”) explicit.

(b) document how these use cases are currently handled by existing systems. That is, document the way such data is currently stored/received from pumps, CGMs, online data sources, or serialized data sources (like downloaded CSV’s).

These tasks are something the open source community could definitely help with. We could even go so far as to ask people to contribute data (which we would store anonymously, of course!), accompanied by a narrative of what was going on, that illustrates interesting events or edge cases. Imagine a big “donate your data” button on the web site…

Once this is done, we can then work together to create a data model that is able to handle all the use cases that we care about.

Maybe this has already been done…but if it has, I haven’t seen it; if so, please direct me there and accept my apologies…

Best,

Chris

**Comment by cheddar** [comment]
On the naming.  What I'm trying to say is that attaching an adjective like "expectedDuration" or "predictedDuration" or whatever, implies that there might be a just plain old "duration" with different semantics.  However, that semantic differentiation will actually never occur.  To the reporter of the data, it must report what it believes to be true, and the read-side of the data must also trust that what it got is the best possible information.  There's no escaping that and therefore I think that adding adjectives will actually serve to confuse instead of exemplify.  That said, I don't care much about naming, if that's all we're discussing, I'm perfectly fine with calling it "xxxDuration" and letting the future decide.

On documenting all of the use cases and everything.  I think that's a great idea.  In fact, it was already started by Brandon and Jana at https://github.com/tidepool-org/data-model/wiki

However, what's documented there is the visualization data model (what the viz wants in order to show prettiness), which might or might not actually line up with the tidepool data model.  My proposal here to add "duration" actually lines the two up more than they are currently (the current "model" doesn't have a duration on scheduled basals).  

As far as applicability of the data model we are using right now, we know that we can convert from two separate sources into the model.  It's pretty easy for me to imagine generating these events if I were writing the software that handles a pump or CGM myself.  The things that I don't believe we have enough coverage of are real-world scenarios and a full understanding of how device manufacturers think of the data they are generating.

The first one will only come from having users and running into issues.  Asking for donations and things as you mention is a great way to help bootstrap this, but learning from actual user data is going to be the best thing for us moving forward.

For the second thing, we need to be able to have conversations with actual engineers at device manufacturers' in order to get a good sense of how they think.  In order to have a productive conversation with an engineer, I believe we need a proposal in place first.  Without a concrete proposal, you are stuck talking in the abstract and often leave the conversation with less clarity than when you entered.

Long story short, I do not think we should delay a v1 straw man of the data format that we currently use in order to come up with a "perfect" data model that will cover everything.  Instead, we need to get something to iterate on out quickly and fish it amongst whoever is willing to iterate on it with us.  Will it be wrong?  Yes.  I believe that concrete wrongness will get us to something that is right a lot quicker than leaving things as high-level, abstract, thought exercises.

Lastly, it could be that I read too deeply into what you are saying.  Your comments could simply be the result of a lack of clear explanation of the data format on my part.  That is very possible as I filled in the bare minimum to explain what a "temp-stop" is and why we need it.  Fwiw, I consider the document in this PR maybe 10 or 15% complete.

**Comment by brandonarbiter** [comment]
Bolus is a good analogy for where there is an "estimated" (or expected) and
"actual". Currently, the semantics don't matter because we're talking about
"expected" and we are not talk about "actual". Why, @cheddar, are you
presuming that we don't or shouldn't include both, the way we do with bolus
delivery? It can be calculated based on basal schedule change or temp basal
stop and written into the JSON record post-facto.

To you point about delaying the V1, let's certainly not.

Brandon Arbiter
VP, Product + Biz Dev
Tidepool http://www.tidepool.org | brandon@tidepool.org
917.536.0505 (m)

**Comment by cheddar** [comment]
With boluses, it is actually "programmed" and "value" from carelink, but yes, we do currently have separate fields and that is now something we will have to deal with as well.  We also do not actually visualize the programmed field, nor do we get it from diasend.

The thing I'm trying to figure out, is, assume a device is just emitting events as they happen.  I am believing that we need to be able to visualize as-yet incomplete events just as we need to be able to visualize them when they are complete.

I'm attempting to keep the model as simple as possible, solve the 90% need now and leave the rest as an exercise for the future.  My thinking is that it is simpler on the visualization side to have a single number that we visualize.  That number is as close to correct as we can get given whatever information we have at the time that the data is accessed.  It does seem that these "expected" and "actual" numbers might be a fairly common phenomenon, in which case maybe we do need to store two values on everything, (1) expected and (2) actual, which is equivalent to expected until we are told it is not.

I'm assuming the proposal on the table is to adjust the basals to have an "expectedDuration" and an "actualDuration", if I do that will it resolve people's concerns?

**Comment by brandonarbiter** [comment]
That would resolve things for me.

Brandon Arbiter
VP, Product + Biz Dev
Tidepool http://www.tidepool.org | brandon@tidepool.org
917.536.0505 (m)

**Comment by cmakler** [comment]
Yup, me too.

**Pull request closed without merging**
