### PR TITLE
Bewest/example - developing schemas

### PR DESCRIPTION
**Pull request by bewest**
## using matic and other json-schema tools

This is an attempt to develop a self documenting schema and validator using json-schema and related tools.

### CODE REVIEW

**Comment by bewest** [comment]
Bunch of links:
- http://spacetelescope.github.io/understanding-json-schema/reference/generic.html
- http://www.jsonschema.net/examples.html
- http://json-schema.org/latest/json-schema-validation.html#anchor88
- http://json-schema.org/latest/json-schema-core.html#anchor4
- https://github.com/mattyod/matic-example
- http://kb.knomaton.org/json-schema/#required
- http://tools.ietf.org/html/draft-zyp-json-schema-03
- http://json-schema.org/example2.html
- http://json-schema-validator.herokuapp.com/
- http://jsonschemalint.com/

### validators

I tried several:
- https://github.com/zaggino/z-schema - nice api, but couldn't quite get it working
- JSV - not enough docs on interface
- jsonschema - ended up choosing this one
- looked at tv4 - seems dangerous, process-wide environment http://geraintluff.github.io/tv4/
- 

I also looked at several others, ask me for details if you come across an interesting one.

**Comment by kentquirk** [comment]
So...I see some value in using schemas (although I'm not sure we're at all ready to settle on them because we're going to be changing our JSON pretty rapidly over the next few months).

I don't really see that matic is bringing anything very useful to the party. I don't find the matic docs at all helpful compared to just looking at the schemas themselves.

I don't hate the idea of this, but I just don't see it as particularly valuable at this point.

**Comment by bewest** [comment]
@jebeck how do you feel about this being merged to master?

**Comment by bewest** [comment]
http://tidepool-org.github.io/data-model/ is the basic version, minus our prettified styles, but should serve as decent starting point.

**Comment by bewest** [comment]
[Build Status](https://travis-ci.org/tidepool-org/data-model)

**Comment by bewest** [comment]
@tidepool-org/committers  Front-end and other interested people.

I've developed a set of schemas in order to create a validator.  The validator is a single piece of code I can use to require in the tests for each parser, mmcsv-carelink-data, dexcom-stream, and anim-parser (XX) to ensure that the same smbg and bolus and carb records are coming out of each one.

I also needed a suite of example json files, one for each type of json, with which to test that the validator is using desired schema to differentiate and pass/fail different types of data.

For reference those examples are located here: https://github.com/tidepool-org/data-model/tree/bewest/example/examples/one

They should match exactly what @jebeck has in the wiki, and in the example json from her python script.

Basic process was to copy/paste the examples into http://www.jsonschema.net/ to generate a basic schema skeleton, and then tweak a variety of properties to be much more strict.  Then I used some of the other tools listed above to lint and attempt using the syntax.  Then I used a node library to import the schemas and ensure that they could correctly differentiate between types of data.  Eg. each one refuses to validate other types of data, and only correctly validates it's own example data.

In the json-schema landscape, there is an expectation that the `URL`s used to express namespace also be dereferencable as actual `URI`s.  I used a validator library which allows overriding what the id attribute means, which will allow us to continue bootstrapping the schema appropriately.

> `URL` is any "locator", meaning it doesn't have to be an actual `URI`, which is something that you can reasonably access over the network.  Eg, `urn:foo:bar` is a valid `URL` but not a `URI` because you cannot dereference it.. it's just an id.

In the short term, ensure that no two `id` attributes have the same value.

There is also a tool in `bin/tidepool-validate` which is a well behaved unix commandline, complete with tab completion `--help` and ability to redirect input from `stdin` when given `-` as the input file name.

**Pull request merged**
